// Code generated by ent, DO NOT EDIT.

package light

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the light type in the database.
	Label = "light"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrivateField holds the string denoting the private_field field in the database.
	FieldPrivateField = "private_field"
	// Table holds the table name of the light in the database.
	Table = "lights"
)

// Columns holds all SQL columns for light fields.
var Columns = []string{
	FieldID,
	FieldPrivateField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Light queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrivateField orders the results by the private_field field.
func ByPrivateField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateField, opts...).ToFunc()
}
