// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Light is the predicate function for light builders.
type Light func(*sql.Selector)

// PlayerFavoriteCards is the predicate function for playerfavoritecards builders.
type PlayerFavoriteCards func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
