// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/entvis/_examples/users/internal/database/ent/light"
	"github.com/yyewolf/entvis/_examples/users/internal/database/ent/predicate"
)

// LightUpdate is the builder for updating Light entities.
type LightUpdate struct {
	config
	hooks    []Hook
	mutation *LightMutation
}

// Where appends a list predicates to the LightUpdate builder.
func (lu *LightUpdate) Where(ps ...predicate.Light) *LightUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetPrivateField sets the "private_field" field.
func (lu *LightUpdate) SetPrivateField(s string) *LightUpdate {
	lu.mutation.SetPrivateField(s)
	return lu
}

// SetNillablePrivateField sets the "private_field" field if the given value is not nil.
func (lu *LightUpdate) SetNillablePrivateField(s *string) *LightUpdate {
	if s != nil {
		lu.SetPrivateField(*s)
	}
	return lu
}

// ClearPrivateField clears the value of the "private_field" field.
func (lu *LightUpdate) ClearPrivateField() *LightUpdate {
	lu.mutation.ClearPrivateField()
	return lu
}

// Mutation returns the LightMutation object of the builder.
func (lu *LightUpdate) Mutation() *LightMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LightUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LightUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LightUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lu *LightUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(light.Table, light.Columns, sqlgraph.NewFieldSpec(light.FieldID, field.TypeString))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.PrivateField(); ok {
		_spec.SetField(light.FieldPrivateField, field.TypeString, value)
	}
	if lu.mutation.PrivateFieldCleared() {
		_spec.ClearField(light.FieldPrivateField, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{light.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LightUpdateOne is the builder for updating a single Light entity.
type LightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LightMutation
}

// SetPrivateField sets the "private_field" field.
func (luo *LightUpdateOne) SetPrivateField(s string) *LightUpdateOne {
	luo.mutation.SetPrivateField(s)
	return luo
}

// SetNillablePrivateField sets the "private_field" field if the given value is not nil.
func (luo *LightUpdateOne) SetNillablePrivateField(s *string) *LightUpdateOne {
	if s != nil {
		luo.SetPrivateField(*s)
	}
	return luo
}

// ClearPrivateField clears the value of the "private_field" field.
func (luo *LightUpdateOne) ClearPrivateField() *LightUpdateOne {
	luo.mutation.ClearPrivateField()
	return luo
}

// Mutation returns the LightMutation object of the builder.
func (luo *LightUpdateOne) Mutation() *LightMutation {
	return luo.mutation
}

// Where appends a list predicates to the LightUpdate builder.
func (luo *LightUpdateOne) Where(ps ...predicate.Light) *LightUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LightUpdateOne) Select(field string, fields ...string) *LightUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Light entity.
func (luo *LightUpdateOne) Save(ctx context.Context) (*Light, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LightUpdateOne) SaveX(ctx context.Context) *Light {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LightUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LightUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luo *LightUpdateOne) sqlSave(ctx context.Context) (_node *Light, err error) {
	_spec := sqlgraph.NewUpdateSpec(light.Table, light.Columns, sqlgraph.NewFieldSpec(light.FieldID, field.TypeString))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Light.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, light.FieldID)
		for _, f := range fields {
			if !light.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != light.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.PrivateField(); ok {
		_spec.SetField(light.FieldPrivateField, field.TypeString, value)
	}
	if luo.mutation.PrivateFieldCleared() {
		_spec.ClearField(light.FieldPrivateField, field.TypeString)
	}
	_node = &Light{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{light.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
