// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/entvis/_examples/users/internal/database/ent/light"
)

// LightCreate is the builder for creating a Light entity.
type LightCreate struct {
	config
	mutation *LightMutation
	hooks    []Hook
}

// SetPrivateField sets the "private_field" field.
func (lc *LightCreate) SetPrivateField(s string) *LightCreate {
	lc.mutation.SetPrivateField(s)
	return lc
}

// SetNillablePrivateField sets the "private_field" field if the given value is not nil.
func (lc *LightCreate) SetNillablePrivateField(s *string) *LightCreate {
	if s != nil {
		lc.SetPrivateField(*s)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LightCreate) SetID(s string) *LightCreate {
	lc.mutation.SetID(s)
	return lc
}

// Mutation returns the LightMutation object of the builder.
func (lc *LightCreate) Mutation() *LightMutation {
	return lc.mutation
}

// Save creates the Light in the database.
func (lc *LightCreate) Save(ctx context.Context) (*Light, error) {
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LightCreate) SaveX(ctx context.Context) *Light {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LightCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LightCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LightCreate) check() error {
	return nil
}

func (lc *LightCreate) sqlSave(ctx context.Context) (*Light, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Light.ID type: %T", _spec.ID.Value)
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LightCreate) createSpec() (*Light, *sqlgraph.CreateSpec) {
	var (
		_node = &Light{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(light.Table, sqlgraph.NewFieldSpec(light.FieldID, field.TypeString))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lc.mutation.PrivateField(); ok {
		_spec.SetField(light.FieldPrivateField, field.TypeString, value)
		_node.PrivateField = value
	}
	return _node, _spec
}

// LightCreateBulk is the builder for creating many Light entities in bulk.
type LightCreateBulk struct {
	config
	err      error
	builders []*LightCreate
}

// Save creates the Light entities in the database.
func (lcb *LightCreateBulk) Save(ctx context.Context) ([]*Light, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Light, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LightCreateBulk) SaveX(ctx context.Context) []*Light {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LightCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LightCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
